//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.ServiceTecnicos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTecnicos.ITecnicos")]
    public interface ITecnicos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/ObtenerTecnico", ReplyAction="http://tempuri.org/ITecnicos/ObtenerTecnicoResponse")]
        Entidades.SHMC_EMPL ObtenerTecnico(int COD_TECN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/ObtenerTecnico", ReplyAction="http://tempuri.org/ITecnicos/ObtenerTecnicoResponse")]
        System.Threading.Tasks.Task<Entidades.SHMC_EMPL> ObtenerTecnicoAsync(int COD_TECN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/ListarTecnicos", ReplyAction="http://tempuri.org/ITecnicos/ListarTecnicosResponse")]
        Entidades.SHMC_EMPL[] ListarTecnicos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/ListarTecnicos", ReplyAction="http://tempuri.org/ITecnicos/ListarTecnicosResponse")]
        System.Threading.Tasks.Task<Entidades.SHMC_EMPL[]> ListarTecnicosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITecnicosChannel : WebApp.ServiceTecnicos.ITecnicos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TecnicosClient : System.ServiceModel.ClientBase<WebApp.ServiceTecnicos.ITecnicos>, WebApp.ServiceTecnicos.ITecnicos {
        
        public TecnicosClient() {
        }
        
        public TecnicosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TecnicosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TecnicosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TecnicosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.SHMC_EMPL ObtenerTecnico(int COD_TECN) {
            return base.Channel.ObtenerTecnico(COD_TECN);
        }
        
        public System.Threading.Tasks.Task<Entidades.SHMC_EMPL> ObtenerTecnicoAsync(int COD_TECN) {
            return base.Channel.ObtenerTecnicoAsync(COD_TECN);
        }
        
        public Entidades.SHMC_EMPL[] ListarTecnicos() {
            return base.Channel.ListarTecnicos();
        }
        
        public System.Threading.Tasks.Task<Entidades.SHMC_EMPL[]> ListarTecnicosAsync() {
            return base.Channel.ListarTecnicosAsync();
        }
    }
}
