//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestServices.WCFEquipos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SHMC_EQUI", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class SHMC_EQUI : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_SERIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_ALMAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_EQUIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_ESTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_PUNT_ATENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TECNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPO_UBICField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_SERI {
            get {
                return this.ALF_SERIField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_SERIField, value) != true)) {
                    this.ALF_SERIField = value;
                    this.RaisePropertyChanged("ALF_SERI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_ALMA {
            get {
                return this.COD_ALMAField;
            }
            set {
                if ((this.COD_ALMAField.Equals(value) != true)) {
                    this.COD_ALMAField = value;
                    this.RaisePropertyChanged("COD_ALMA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_EQUI {
            get {
                return this.COD_EQUIField;
            }
            set {
                if ((this.COD_EQUIField.Equals(value) != true)) {
                    this.COD_EQUIField = value;
                    this.RaisePropertyChanged("COD_EQUI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_ESTA {
            get {
                return this.COD_ESTAField;
            }
            set {
                if ((this.COD_ESTAField.Equals(value) != true)) {
                    this.COD_ESTAField = value;
                    this.RaisePropertyChanged("COD_ESTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_PUNT_ATEN {
            get {
                return this.COD_PUNT_ATENField;
            }
            set {
                if ((this.COD_PUNT_ATENField.Equals(value) != true)) {
                    this.COD_PUNT_ATENField = value;
                    this.RaisePropertyChanged("COD_PUNT_ATEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TECN {
            get {
                return this.COD_TECNField;
            }
            set {
                if ((this.COD_TECNField.Equals(value) != true)) {
                    this.COD_TECNField = value;
                    this.RaisePropertyChanged("COD_TECN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO_UBIC {
            get {
                return this.COD_TIPO_UBICField;
            }
            set {
                if ((this.COD_TIPO_UBICField.Equals(value) != true)) {
                    this.COD_TIPO_UBICField = value;
                    this.RaisePropertyChanged("COD_TIPO_UBIC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFEquipos.IEquipos")]
    public interface IEquipos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        TestServices.WCFEquipos.SHMC_EQUI ObtenerEquipo(int COD_EQUI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ObtenerEquipo", ReplyAction="http://tempuri.org/IEquipos/ObtenerEquipoResponse")]
        System.Threading.Tasks.Task<TestServices.WCFEquipos.SHMC_EQUI> ObtenerEquipoAsync(int COD_EQUI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        TestServices.WCFEquipos.SHMC_EQUI ModificarEquipo(TestServices.WCFEquipos.SHMC_EQUI equipoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ModificarEquipo", ReplyAction="http://tempuri.org/IEquipos/ModificarEquipoResponse")]
        System.Threading.Tasks.Task<TestServices.WCFEquipos.SHMC_EQUI> ModificarEquipoAsync(TestServices.WCFEquipos.SHMC_EQUI equipoAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        TestServices.WCFEquipos.SHMC_EQUI[] ListarEquipos(int COD_TECN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEquipos/ListarEquipos", ReplyAction="http://tempuri.org/IEquipos/ListarEquiposResponse")]
        System.Threading.Tasks.Task<TestServices.WCFEquipos.SHMC_EQUI[]> ListarEquiposAsync(int COD_TECN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEquiposChannel : TestServices.WCFEquipos.IEquipos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquiposClient : System.ServiceModel.ClientBase<TestServices.WCFEquipos.IEquipos>, TestServices.WCFEquipos.IEquipos {
        
        public EquiposClient() {
        }
        
        public EquiposClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquiposClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquiposClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestServices.WCFEquipos.SHMC_EQUI ObtenerEquipo(int COD_EQUI) {
            return base.Channel.ObtenerEquipo(COD_EQUI);
        }
        
        public System.Threading.Tasks.Task<TestServices.WCFEquipos.SHMC_EQUI> ObtenerEquipoAsync(int COD_EQUI) {
            return base.Channel.ObtenerEquipoAsync(COD_EQUI);
        }
        
        public TestServices.WCFEquipos.SHMC_EQUI ModificarEquipo(TestServices.WCFEquipos.SHMC_EQUI equipoAModificar) {
            return base.Channel.ModificarEquipo(equipoAModificar);
        }
        
        public System.Threading.Tasks.Task<TestServices.WCFEquipos.SHMC_EQUI> ModificarEquipoAsync(TestServices.WCFEquipos.SHMC_EQUI equipoAModificar) {
            return base.Channel.ModificarEquipoAsync(equipoAModificar);
        }
        
        public TestServices.WCFEquipos.SHMC_EQUI[] ListarEquipos(int COD_TECN) {
            return base.Channel.ListarEquipos(COD_TECN);
        }
        
        public System.Threading.Tasks.Task<TestServices.WCFEquipos.SHMC_EQUI[]> ListarEquiposAsync(int COD_TECN) {
            return base.Channel.ListarEquiposAsync(COD_TECN);
        }
    }
}
