//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject.AtencionesWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SHMC_ATEN", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    [System.SerializableAttribute()]
    public partial class SHMC_ATEN : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ALF_COMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_ATENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_ESTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_PUNT_ATENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TECNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int COD_TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_ATENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FEC_PROGField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ALF_COME {
            get {
                return this.ALF_COMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ALF_COMEField, value) != true)) {
                    this.ALF_COMEField = value;
                    this.RaisePropertyChanged("ALF_COME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_ATEN {
            get {
                return this.COD_ATENField;
            }
            set {
                if ((this.COD_ATENField.Equals(value) != true)) {
                    this.COD_ATENField = value;
                    this.RaisePropertyChanged("COD_ATEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_ESTA {
            get {
                return this.COD_ESTAField;
            }
            set {
                if ((this.COD_ESTAField.Equals(value) != true)) {
                    this.COD_ESTAField = value;
                    this.RaisePropertyChanged("COD_ESTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_PUNT_ATEN {
            get {
                return this.COD_PUNT_ATENField;
            }
            set {
                if ((this.COD_PUNT_ATENField.Equals(value) != true)) {
                    this.COD_PUNT_ATENField = value;
                    this.RaisePropertyChanged("COD_PUNT_ATEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TECN {
            get {
                return this.COD_TECNField;
            }
            set {
                if ((this.COD_TECNField.Equals(value) != true)) {
                    this.COD_TECNField = value;
                    this.RaisePropertyChanged("COD_TECN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COD_TIPO {
            get {
                return this.COD_TIPOField;
            }
            set {
                if ((this.COD_TIPOField.Equals(value) != true)) {
                    this.COD_TIPOField = value;
                    this.RaisePropertyChanged("COD_TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_ATEN {
            get {
                return this.FEC_ATENField;
            }
            set {
                if ((this.FEC_ATENField.Equals(value) != true)) {
                    this.FEC_ATENField = value;
                    this.RaisePropertyChanged("FEC_ATEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FEC_PROG {
            get {
                return this.FEC_PROGField;
            }
            set {
                if ((this.FEC_PROGField.Equals(value) != true)) {
                    this.FEC_PROGField = value;
                    this.RaisePropertyChanged("FEC_PROG");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices.Errores")]
    [System.SerializableAttribute()]
    public partial class GeneralException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtencionesWS.IAtenciones")]
    public interface IAtenciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/CrearAtencion", ReplyAction="http://tempuri.org/IAtenciones/CrearAtencionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UnitTestProject.AtencionesWS.GeneralException), Action="http://tempuri.org/IAtenciones/CrearAtencionGeneralExceptionFault", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices.Errores")]
        UnitTestProject.AtencionesWS.SHMC_ATEN CrearAtencion(UnitTestProject.AtencionesWS.SHMC_ATEN atencionACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/CrearAtencion", ReplyAction="http://tempuri.org/IAtenciones/CrearAtencionResponse")]
        System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN> CrearAtencionAsync(UnitTestProject.AtencionesWS.SHMC_ATEN atencionACrear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/ObtenerAtencion", ReplyAction="http://tempuri.org/IAtenciones/ObtenerAtencionResponse")]
        UnitTestProject.AtencionesWS.SHMC_ATEN ObtenerAtencion(int COD_ATEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/ObtenerAtencion", ReplyAction="http://tempuri.org/IAtenciones/ObtenerAtencionResponse")]
        System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN> ObtenerAtencionAsync(int COD_ATEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/ModificarAtencion", ReplyAction="http://tempuri.org/IAtenciones/ModificarAtencionResponse")]
        UnitTestProject.AtencionesWS.SHMC_ATEN ModificarAtencion(UnitTestProject.AtencionesWS.SHMC_ATEN atencionAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/ModificarAtencion", ReplyAction="http://tempuri.org/IAtenciones/ModificarAtencionResponse")]
        System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN> ModificarAtencionAsync(UnitTestProject.AtencionesWS.SHMC_ATEN atencionAModificar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/EliminarAtencion", ReplyAction="http://tempuri.org/IAtenciones/EliminarAtencionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(UnitTestProject.AtencionesWS.GeneralException), Action="http://tempuri.org/IAtenciones/EliminarAtencionGeneralExceptionFault", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices.Errores")]
        int EliminarAtencion(int COD_ATEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/EliminarAtencion", ReplyAction="http://tempuri.org/IAtenciones/EliminarAtencionResponse")]
        System.Threading.Tasks.Task<int> EliminarAtencionAsync(int COD_ATEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/ListarAtenciones", ReplyAction="http://tempuri.org/IAtenciones/ListarAtencionesResponse")]
        UnitTestProject.AtencionesWS.SHMC_ATEN[] ListarAtenciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAtenciones/ListarAtenciones", ReplyAction="http://tempuri.org/IAtenciones/ListarAtencionesResponse")]
        System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN[]> ListarAtencionesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAtencionesChannel : UnitTestProject.AtencionesWS.IAtenciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AtencionesClient : System.ServiceModel.ClientBase<UnitTestProject.AtencionesWS.IAtenciones>, UnitTestProject.AtencionesWS.IAtenciones {
        
        public AtencionesClient() {
        }
        
        public AtencionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AtencionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtencionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AtencionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public UnitTestProject.AtencionesWS.SHMC_ATEN CrearAtencion(UnitTestProject.AtencionesWS.SHMC_ATEN atencionACrear) {
            return base.Channel.CrearAtencion(atencionACrear);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN> CrearAtencionAsync(UnitTestProject.AtencionesWS.SHMC_ATEN atencionACrear) {
            return base.Channel.CrearAtencionAsync(atencionACrear);
        }
        
        public UnitTestProject.AtencionesWS.SHMC_ATEN ObtenerAtencion(int COD_ATEN) {
            return base.Channel.ObtenerAtencion(COD_ATEN);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN> ObtenerAtencionAsync(int COD_ATEN) {
            return base.Channel.ObtenerAtencionAsync(COD_ATEN);
        }
        
        public UnitTestProject.AtencionesWS.SHMC_ATEN ModificarAtencion(UnitTestProject.AtencionesWS.SHMC_ATEN atencionAModificar) {
            return base.Channel.ModificarAtencion(atencionAModificar);
        }
        
        public System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN> ModificarAtencionAsync(UnitTestProject.AtencionesWS.SHMC_ATEN atencionAModificar) {
            return base.Channel.ModificarAtencionAsync(atencionAModificar);
        }
        
        public int EliminarAtencion(int COD_ATEN) {
            return base.Channel.EliminarAtencion(COD_ATEN);
        }
        
        public System.Threading.Tasks.Task<int> EliminarAtencionAsync(int COD_ATEN) {
            return base.Channel.EliminarAtencionAsync(COD_ATEN);
        }
        
        public UnitTestProject.AtencionesWS.SHMC_ATEN[] ListarAtenciones() {
            return base.Channel.ListarAtenciones();
        }
        
        public System.Threading.Tasks.Task<UnitTestProject.AtencionesWS.SHMC_ATEN[]> ListarAtencionesAsync() {
            return base.Channel.ListarAtencionesAsync();
        }
    }
}
