//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPOSPrototipo.TecnicosWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices.Errores")]
    [System.SerializableAttribute()]
    public partial class GeneralException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TecnicosWS.ITecnicos")]
    public interface ITecnicos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/ListarTecnicos", ReplyAction="http://tempuri.org/ITecnicos/ListarTecnicosResponse")]
        Entidades.SHMC_EMPL[] ListarTecnicos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/ListarTecnicos", ReplyAction="http://tempuri.org/ITecnicos/ListarTecnicosResponse")]
        System.Threading.Tasks.Task<Entidades.SHMC_EMPL[]> ListarTecnicosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/LoginTecnico", ReplyAction="http://tempuri.org/ITecnicos/LoginTecnicoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(DPOSPrototipo.TecnicosWS.GeneralException), Action="http://tempuri.org/ITecnicos/LoginTecnicoGeneralExceptionFault", Name="GeneralException", Namespace="http://schemas.datacontract.org/2004/07/WcfServices.Errores")]
        Entidades.SHMC_USUA LoginTecnico(Entidades.SHMC_USUA usuarioABuscar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITecnicos/LoginTecnico", ReplyAction="http://tempuri.org/ITecnicos/LoginTecnicoResponse")]
        System.Threading.Tasks.Task<Entidades.SHMC_USUA> LoginTecnicoAsync(Entidades.SHMC_USUA usuarioABuscar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITecnicosChannel : DPOSPrototipo.TecnicosWS.ITecnicos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TecnicosClient : System.ServiceModel.ClientBase<DPOSPrototipo.TecnicosWS.ITecnicos>, DPOSPrototipo.TecnicosWS.ITecnicos {
        
        public TecnicosClient() {
        }
        
        public TecnicosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TecnicosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TecnicosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TecnicosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Entidades.SHMC_EMPL[] ListarTecnicos() {
            return base.Channel.ListarTecnicos();
        }
        
        public System.Threading.Tasks.Task<Entidades.SHMC_EMPL[]> ListarTecnicosAsync() {
            return base.Channel.ListarTecnicosAsync();
        }
        
        public Entidades.SHMC_USUA LoginTecnico(Entidades.SHMC_USUA usuarioABuscar) {
            return base.Channel.LoginTecnico(usuarioABuscar);
        }
        
        public System.Threading.Tasks.Task<Entidades.SHMC_USUA> LoginTecnicoAsync(Entidades.SHMC_USUA usuarioABuscar) {
            return base.Channel.LoginTecnicoAsync(usuarioABuscar);
        }
    }
}
