//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPOSPrototipo.FacilidadesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FacilidadesWS.IFacilidades")]
    public interface IFacilidades {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilidades/RegistrarAtencionFacilidad", ReplyAction="http://tempuri.org/IFacilidades/RegistrarAtencionFacilidadResponse")]
        int RegistrarAtencionFacilidad(Entidades.SHMD_ATEN_REPO_FACI atenfaciARegistrar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilidades/RegistrarAtencionFacilidad", ReplyAction="http://tempuri.org/IFacilidades/RegistrarAtencionFacilidadResponse")]
        System.Threading.Tasks.Task<int> RegistrarAtencionFacilidadAsync(Entidades.SHMD_ATEN_REPO_FACI atenfaciARegistrar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilidades/ListarFacilidades", ReplyAction="http://tempuri.org/IFacilidades/ListarFacilidadesResponse")]
        System.Collections.Generic.List<Entidades.SHMC_FACI> ListarFacilidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFacilidades/ListarFacilidades", ReplyAction="http://tempuri.org/IFacilidades/ListarFacilidadesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SHMC_FACI>> ListarFacilidadesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFacilidadesChannel : DPOSPrototipo.FacilidadesWS.IFacilidades, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FacilidadesClient : System.ServiceModel.ClientBase<DPOSPrototipo.FacilidadesWS.IFacilidades>, DPOSPrototipo.FacilidadesWS.IFacilidades {
        
        public FacilidadesClient() {
        }
        
        public FacilidadesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FacilidadesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacilidadesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FacilidadesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int RegistrarAtencionFacilidad(Entidades.SHMD_ATEN_REPO_FACI atenfaciARegistrar) {
            return base.Channel.RegistrarAtencionFacilidad(atenfaciARegistrar);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarAtencionFacilidadAsync(Entidades.SHMD_ATEN_REPO_FACI atenfaciARegistrar) {
            return base.Channel.RegistrarAtencionFacilidadAsync(atenfaciARegistrar);
        }
        
        public System.Collections.Generic.List<Entidades.SHMC_FACI> ListarFacilidades() {
            return base.Channel.ListarFacilidades();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Entidades.SHMC_FACI>> ListarFacilidadesAsync() {
            return base.Channel.ListarFacilidadesAsync();
        }
    }
}
